apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-gateway

resources:
  - ../../base

images:
  - name: oci.arsalan.io/nvidia-ida/approval-console
    digest: sha256:31c77ea913480564fadc1e831f7ffb489a1ed9e8552fb3903e8cc6e9d15bc5ff

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: approval-console
