apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-gateway

resources:
  - namespace.yaml
  - gateway.yaml
  - route-openshift.yaml
  - backend-pfsense-mcp.yaml
  - httproute-mcp.yaml
  - policy.yaml
  - networkpolicies.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: agentic-platform
