apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-ida-isolation
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: nvidia-ida

  source:
    repoURL: https://git.arsalan.io/anaeem/nvidia-ida.git
    targetRevision: main
    path: platform/isolation/kata-runtimeclass

  destination:
    server: https://api.anaeem.na-launch.com:6443
    namespace: agent-sandbox

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
