apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-ida-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: nvidia-ida

  source:
    repoURL: https://git.arsalan.io/anaeem/nvidia-ida.git
    targetRevision: fix/jit-approver-mint-route
    path: platform/00-operators

  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators   # cluster-scoped resources land here by convention

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
