apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-authz-server
  namespace: kyverno
  labels:
    app.kubernetes.io/name: kyverno-authz-server
    app.kubernetes.io/component: authz-server
    app.kubernetes.io/part-of: nvidia-ida
  annotations:
    # SPIFFE SVID will be:
    # spiffe://anaeem.na-launch.com/ns/kyverno/sa/kyverno-authz-server
automountServiceAccountToken: false
