apiVersion: v1
kind: Namespace
metadata:
  name: agentic-observability
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: nvidia-ida
    openshift.io/cluster-monitoring: "true"
