apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-kata-runtimeclass.yaml
  - disallow-default-sa-automount.yaml
  - require-networkpolicy.yaml
  - restrict-image-registries.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: nvidia-ida
      app.kubernetes.io/component: kyverno-guardrails
