apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-gateway

resources:
  - ../../base

images:
  - name: oci.arsalan.io/nvidia-ida/sandbox-launcher
    newTag: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: sandbox-launcher
